# Generated by Django 5.2.7 on 2025-11-01 19:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo de Conta',
                'verbose_name_plural': 'Grupos de Contas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conta', models.CharField(help_text='Nome identificador da conta', max_length=200, verbose_name='Nome da Conta')),
                ('fixo_variado', models.CharField(choices=[('fixo', 'Fixo'), ('variado', 'Variado')], default='variado', max_length=10, verbose_name='Fixo ou Variado')),
                ('recorrencia', models.CharField(choices=[('unica', 'Única'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='unica', max_length=20, verbose_name='Recorrência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('nome_razao', models.CharField(blank=True, max_length=200, verbose_name='Nome/Razão Social')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='Formato: 000.000.000-00 ou 00.000.000/0000-00', max_length=18, verbose_name='CPF/CNPJ')),
                ('tipo_pagamento', models.CharField(blank=True, choices=[('transferencia', 'Transferência'), ('deposito', 'Depósito'), ('pix', 'Pix')], max_length=20, verbose_name='Transferência/Depósito/Pix')),
                ('numero_conta_pix', models.CharField(blank=True, max_length=100, verbose_name='Número da Conta ou Pix')),
                ('agencia', models.CharField(blank=True, max_length=10, verbose_name='Agência')),
                ('conta_corrente_poupanca', models.CharField(blank=True, max_length=50, verbose_name='Conta Corrente/Poupança')),
                ('banco_origem', models.CharField(blank=True, max_length=100, verbose_name='Banco Origem')),
                ('modelo', models.CharField(blank=True, help_text='Modelo do veículo (se aplicável)', max_length=100, verbose_name='Modelo')),
                ('placa', models.CharField(blank=True, max_length=10, verbose_name='Placa')),
                ('renavam', models.CharField(blank=True, max_length=11, verbose_name='Renavam')),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Fabricação')),
                ('ipva_multa', models.BooleanField(default=False, verbose_name='IPVA/IPVA + Multa')),
                ('link_acesso_pagamento', models.URLField(blank=True, max_length=500, verbose_name='Link de Acesso para Pagar a Conta')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuário')),
                ('senha', models.CharField(blank=True, help_text='Considere usar criptografia para armazenar senhas', max_length=100, verbose_name='Senha')),
                ('whatsapp_confirmacao', models.CharField(blank=True, help_text='Formato: (00) 00000-0000', max_length=20, verbose_name='WhatsApp para Confirmação de Pagamento')),
                ('link_passo_passo', models.URLField(blank=True, max_length=500, verbose_name='Link Passo-a-Passo')),
                ('descricao_observacao', models.TextField(blank=True, verbose_name='Descrição ou Observação')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='pay.grupoconta', verbose_name='Grupo de Conta')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_vencimento'],
                'indexes': [models.Index(fields=['data_vencimento', 'pago'], name='pay_contapa_data_ve_c07b19_idx'), models.Index(fields=['grupo_conta', 'data_vencimento'], name='pay_contapa_grupo_c_9fb3ba_idx')],
            },
        ),
    ]
