# Generated by Django 5.2.7 on 2025-11-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoconta',
            name='ativo',
            field=models.BooleanField(default=True, null=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='grupoconta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='grupoconta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='grupoconta',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='grupoconta',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
