# Generated by Django 5.2.7 on 2025-11-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_faturamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='fixo_variado',
            field=models.CharField(choices=[('fixo', 'Fixo'), ('variado', 'Variado')], max_length=10, verbose_name='Fixo ou Variado'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='recorrencia',
            field=models.CharField(choices=[('unica', 'Única'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20, verbose_name='Recorrência'),
        ),
    ]
