# Generated by Django 5.2.7 on 2025-11-08 19:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_alter_contapagar_fixo_variado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='FaturamentoCelcoin_Cartao',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento'),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='FaturamentoEfiBank_Boleto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento'),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='FaturamentoMaquinaCartao',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento'),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='FaturamentoModoBank_Cartao',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento'),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='FaturamentoModoBank_PIX',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento'),
        ),
    ]
