# Generated by Django 5.2.7 on 2025-11-08 20:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_faturamento_faturamentocelcoin_cartao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='FaturamentoCelcoin_Cartao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento Celcoin Cartão'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='FaturamentoEfiBank_Boleto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento EfiBank Boleto'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='FaturamentoMaquinaCartao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento Maquina Cartão'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='FaturamentoModoBank_Cartao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento ModoBank Cartão'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='FaturamentoModoBank_PIX',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento ModoBank PIX'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento Bruto Total'),
        ),
    ]
