# Generated by Django 5.2.7 on 2025-11-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_alter_faturamento_faturamentocelcoin_cartao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapagar',
            name='link_acesso_pagamento',
        ),
        migrations.AddField(
            model_name='contapagar',
            name='video_tutorial',
            field=models.FileField(blank=True, help_text='Faça upload de um vídeo tutorial (MP4, AVI, MOV - máx 100MB)', null=True, upload_to='tutoriais/%Y/%m/', verbose_name='Vídeo Tutorial'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='numero_conta_pix',
            field=models.CharField(blank=True, max_length=300, verbose_name='Número da Conta ou Pix'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='tipo_pagamento',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferência'), ('deposito', 'Depósito'), ('pix_cpf', 'Pix CPF'), ('pix_cnpj', 'Pix CNPJ'), ('pix_email', 'Pix E-mail'), ('pix_telefone', 'Pix Telefone'), ('pix_chave_aleatoria', 'Pix Chave Aleatória'), ('especie', 'Espécie (Dinheiro)')], max_length=20, verbose_name='Transferência/Depósito/Pix'),
        ),
    ]
