# Generated by Django 5.2.7 on 2025-11-08 21:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_remove_contapagar_link_passo_passo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='FaturamentoLoja',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento Loja'),
        ),
    ]
