# Generated by Django 5.2.7 on 2025-11-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0009_faturamento_faturamentoloja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='tipo_pagamento',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferência'), ('deposito', 'Depósito'), ('pix_cpf', 'Pix CPF'), ('pix_cnpj', 'Pix CNPJ'), ('pix_email', 'Pix E-mail'), ('pix_telefone', 'Pix Telefone'), ('pix_chave_aleatoria', 'Pix Chave Aleatória'), ('especie', 'Espécie (Dinheiro)'), ('boleto', 'Boleto Bancário'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('debito_automatico', 'Débito Automático'), ('link_pagamento', 'Link de Pagamento'), ('pix_qr_code', 'Pix QR Code')], max_length=20, verbose_name='Transferência/Depósito/Pix'),
        ),
    ]
