# Generated by Django 5.2.7 on 2025-11-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0010_alter_contapagar_tipo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='nome_pix',
            field=models.CharField(blank=True, max_length=300, verbose_name='Número da Conta ou Pix'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='ipva_multa',
            field=models.CharField(default='False', max_length=10, null=True, verbose_name='IPVA/IPVA + Multa'),
        ),
    ]
