# Generated by Django 5.2.7 on 2025-11-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0011_contapagar_nome_pix_alter_contapagar_ipva_multa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='ipva_multa',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='False', max_length=10, null=True, verbose_name='IPVA/IPVA + Multa'),
        ),
    ]
