# Generated by Django 5.2.7 on 2025-11-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0012_alter_contapagar_ipva_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='alertar_dias_antes',
            field=models.PositiveIntegerField(default=0, help_text='Número de dias antes do vencimento para enviar o alerta.', verbose_name='Alertar quantos dias antes'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='banco_origem',
            field=models.CharField(blank=True, choices=[('caixa', 'Caixa Econômica Federal'), ('bb', 'Banco do Brasil'), ('itau', 'Itaú Unibanco'), ('bradesco', 'Bradesco'), ('santander', 'Santander Brasil'), ('nubank', 'Nubank'), ('inter', 'Banco Inter'), ('c6', 'C6 Bank'), ('original', 'Banco Original'), ('pan', 'Banco Pan'), ('safra', 'Banco Safra'), ('mercantil', 'Banco Mercantil do Brasil'), ('banrisul', 'Banrisul (Banco do Estado do Rio Grande do Sul)'), ('bv', 'Banco Votorantim (BV)'), ('daycoval', 'Banco Daycoval'), ('bs2', 'Banco BS2'), ('digio', 'Banco Digio'), ('sicredi', 'Banco Cooperativo Sicredi'), ('sicoob', 'Banco Cooperativo Sicoob'), ('bnb', 'Banco do Nordeste do Brasil'), ('banestes', 'Banestes (Banco do Estado do Espírito Santo)'), ('alfa', 'Banco Alfa'), ('modal', 'Banco Modal'), ('pine', 'Banco Pine'), ('rendimento', 'Banco Rendimento'), ('rodobens', 'Banco Rodobens'), ('amazonia', 'Banco da Amazônia'), ('kebhana', 'Banco KEB Hana do Brasil'), ('johndeere', 'Banco John Deere'), ('mizuho', 'Banco Mizuho do Brasil'), ('outros', 'Outros não cadastrados')], max_length=100, verbose_name='Banco de Origem'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='conta_corrente_poupanca',
            field=models.CharField(blank=True, choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança'), ('pix', 'Pix')], max_length=50, verbose_name='Conta Corrente ou Poupança'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='fixo_variado',
            field=models.CharField(choices=[('fixo', 'Fixo'), ('variado', 'Variado')], max_length=10, verbose_name='Valor Fixo ou Variado'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='ipva_multa',
            field=models.CharField(choices=[('ipva', 'IPVA'), ('multa', 'Multa'), ('ipva+multa', 'IPVA + Multa')], max_length=10, null=True, verbose_name='IPVA/Multa'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='nome_pix',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nome da Conta ou Pix'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='recorrencia',
            field=models.CharField(choices=[('unica', 'Única'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20, verbose_name='Recorrência'),
        ),
    ]
