# Generated by Django 5.2.7 on 2025-11-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0013_contapagar_alertar_dias_antes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='status',
            field=models.CharField(blank=True, choices=[('em_dia', '🟢 Em Dia'), ('prox_vencer', '🟡 Próximo a Vencer'), ('vence_hoje', '🟠 Vence Hoje'), ('atrasado', '🔴 Em Atraso')], default='em_dia', max_length=20, verbose_name='Status da Conta'),
        ),
    ]
