# Generated by Django 5.2.7 on 2025-11-30 01:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0014_contapagar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='whatsapp_contato_alerta',
            field=models.CharField(blank=True, help_text='Formato: (00) 00000-0000', max_length=20, verbose_name='WhatsApp para Contato de Alerta'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='ipva_multa',
            field=models.CharField(blank=True, choices=[('ipva', 'IPVA'), ('multa', 'Multa'), ('ipva+multa', 'IPVA + Multa')], max_length=10, null=True, verbose_name='IPVA/Multa'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='FaturamentoCelcoin_Cartao',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento Celcoin Cartão'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='FaturamentoEfiBank_Boleto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento EfiBank Boleto'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='FaturamentoLoja',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento Loja'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='FaturamentoMaquinaCartao',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento Maquina Cartão'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='FaturamentoModoBank_Cartao',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento ModoBank Cartão'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='FaturamentoModoBank_PIX',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Faturamento ModoBank PIX'),
        ),
    ]
