# Generated by Django 5.2.7 on 2025-12-18 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0015_contapagar_whatsapp_contato_alerta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='status',
            field=models.CharField(blank=True, choices=[('em_dia', '🟢 Em Dia'), ('prox_vencer', '🟡 Próximo a Vencer'), ('vence_hoje', '🟠 Vence Hoje'), ('atrasado', '🔴 Em Atraso'), ('pago', '✅ Pago')], default='em_dia', max_length=20, verbose_name='Status da Conta'),
        ),
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conta', models.CharField(max_length=200, verbose_name='Nome da Conta')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('data_vencimento_original', models.DateField(verbose_name='Data de Vencimento Original')),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('dias_atraso', models.IntegerField(default=0, verbose_name='Dias de Atraso')),
                ('tipo_pagamento', models.CharField(blank=True, max_length=20, verbose_name='Tipo de Pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_pagamentos', to='pay.contapagar', verbose_name='Conta')),
                ('grupo_conta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pay.grupoconta', verbose_name='Grupo de Conta')),
            ],
            options={
                'verbose_name': 'Histórico de Pagamento',
                'verbose_name_plural': 'Históricos de Pagamentos',
                'ordering': ['-data_pagamento'],
                'indexes': [models.Index(fields=['conta', 'data_pagamento'], name='pay_histori_conta_i_5ed806_idx'), models.Index(fields=['data_pagamento'], name='pay_histori_data_pa_2541f1_idx')],
            },
        ),
    ]
