# Generated by Django 5.2.7 on 2025-12-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0016_alter_contapagar_status_historicopagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='mensagem_confirmacao',
            field=models.TextField(blank=True, help_text='Mensagem que será enviada ao cliente quando a conta for paga. Use {{nome_conta}}, {{valor}}, {{data_pagamento}}', verbose_name='Mensagem de Confirmação de Pagamento'),
        ),
    ]
